# The basics of numpy array

# Numpy array attributes

In [2]:
import numpy as np

In [5]:
np.random.seed(0)

In [12]:
x1 = np.random.randint(10, size = 6)
x1

array([1, 2, 4, 2, 0, 3])

In [13]:
x2 = np.random.randint(10, size = (3,4))
x2

array([[2, 0, 7, 5],
       [9, 0, 2, 7],
       [2, 9, 2, 3]])

In [14]:
x3 = np.random.randint(10, size = (3,4,5))
x3

array([[[3, 2, 3, 4, 1],
        [2, 9, 1, 4, 6],
        [8, 2, 3, 0, 0],
        [6, 0, 6, 3, 3]],

       [[8, 8, 8, 2, 3],
        [2, 0, 8, 8, 3],
        [8, 2, 8, 4, 3],
        [0, 4, 3, 6, 9]],

       [[8, 0, 8, 5, 9],
        [0, 9, 6, 5, 3],
        [1, 8, 0, 4, 9],
        [6, 5, 7, 8, 8]]])

In [16]:
x3.ndim

3

In [18]:
x3.shape

(3, 4, 5)

In [20]:
x3.size

60

In [22]:
x3.dtype

dtype('int32')

In [24]:
x3.itemsize

4

In [26]:
x3.nbytes

240

# Array indexing : accessing single elements

In [28]:
x1

array([1, 2, 4, 2, 0, 3])

In [30]:
x1[0]

1

In [32]:
x1[3]

2

In [34]:
x1[-2]

0

In [36]:
x1[-3]

2

In [38]:
x2

array([[2, 0, 7, 5],
       [9, 0, 2, 7],
       [2, 9, 2, 3]])

In [40]:
x2[0,2]

7

In [42]:
x2[2,2]

2

In [44]:
x1[0] = 2
x1

array([2, 2, 4, 2, 0, 3])

# Array slicing : Accessing subarrays

In [46]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x[1:4]

array([1, 2, 3])

In [50]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [52]:
x[::2]

array([0, 2, 4, 6, 8])

In [54]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [56]:
x[5::-2]

array([5, 3, 1])

# Multidimensional subarray

In [58]:
x2

array([[2, 0, 7, 5],
       [9, 0, 2, 7],
       [2, 9, 2, 3]])

In [60]:
x2[:2,:3]

array([[2, 0, 7],
       [9, 0, 2]])

In [62]:
x2[::-1,::-1]

array([[3, 2, 9, 2],
       [7, 2, 0, 9],
       [5, 7, 0, 2]])

In [64]:
x2[:3,:2]

array([[2, 0],
       [9, 0],
       [2, 9]])

# Accessing array rows and columns

In [66]:
x2

array([[2, 0, 7, 5],
       [9, 0, 2, 7],
       [2, 9, 2, 3]])

In [68]:
x2[:,0]

array([2, 9, 2])

In [70]:
x2[0,:]

array([2, 0, 7, 5])

In [72]:
x2_sub = x2[:2,:2]
x2_sub

array([[2, 0],
       [9, 0]])

In [74]:
x2_sub[0] = 99
x2_sub

array([[99, 99],
       [ 9,  0]])

# Creating copies of arrays

In [76]:
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[99, 99],
       [ 9,  0]])

In [78]:
x2_sub_copy[0,0] = 42
x2_sub_copy

array([[42, 99],
       [ 9,  0]])

In [80]:
x2

array([[99, 99,  7,  5],
       [ 9,  0,  2,  7],
       [ 2,  9,  2,  3]])

# Reshaping of array

In [83]:
grid = np.arange(1,10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
x = np.array([1,2,3])
x.reshape(1,3)
x

array([1, 2, 3])

In [87]:
x.reshape(3,1)
x

array([1, 2, 3])

# Concatenation of arrays

In [90]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [92]:
z = np.array([9,8,7])
np.concatenate([x,y,z])

array([1, 2, 3, 3, 2, 1, 9, 8, 7])

In [94]:
grid = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.concatenate([grid,grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

# Vertical stack and Horizontal stack

In [98]:
grid = np.array([[9,8,7],
                [6,5,4]])
x = np.array([1,2,3])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [102]:
y = np.array([[99],
             [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Splitting the arrays

In [105]:
x = np.array([1,2,3,99,99,3,2,1])
x1,x2,x3 = np.split(x,[3,5])
x1

array([1, 2, 3])

In [107]:
x2

array([99, 99])

In [109]:
x3

array([3, 2, 1])

In [112]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
upper,lower = np.vsplit(grid,[2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [116]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
left,right = np.hsplit(grid,[2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [120]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# View and copy

In [122]:
x = np.array([1,2,3,4,5])

In [124]:
y = x.copy()
y[0] = 3
y

array([3, 2, 3, 4, 5])

In [126]:
x

array([1, 2, 3, 4, 5])

In [128]:
z = x.view()
z[4] = 6
z

array([1, 2, 3, 4, 6])

In [129]:
x

array([1, 2, 3, 4, 6])