# 1. write a numpy program to get the numpy version and show numpy build in configuration

In [2]:
import numpy as np
np.__version__

'1.21.5'

In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baselin

# 2. Write a numpy program to get help on the add function

In [6]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# 3. Write a numpy program to test whether none of the elements of a given array is zero

In [8]:
import numpy as np
x = np.array([1,2,3,4])
np.all(x)

True

In [10]:
y = np.array([0,1,2,3,4])
np.all(y)

False

# 4. Write a numpy program to test whether any of the elements of a given array is non - zero

In [12]:
import numpy as np
x = np.array([1,0,0,0,0,0])
np.any(x)

True

In [15]:
y = np.array([0,0,0,0,0])
np.any(y)

False

# 5. Write a numpy program to test a given array element - wise for finiteness (not infinite or not a number)

In [17]:
import numpy as np
x = np.array([1,0,np.nan,np.inf])
np.isfinite(x)

array([ True,  True, False, False])

# 6. Write a numpy program to test element - wise for positive or negative infinity

In [19]:
import numpy as np
x = np.array([1,0,np.nan,np.inf])
np.isinf(x)

array([False, False, False,  True])

# 7. Write a numpy program to test element - wise for complex number, real number of a given array. Also test whether a number is scalar or not

In [21]:
import numpy as np
x = np.array([1+1j, 1+0j, 4.5, 3,2,2j])
np.iscomplex(x)

array([ True, False, False, False, False,  True])

In [23]:
np.isreal(x)

array([False,  True,  True,  True,  True, False])

In [25]:
np.isscalar(3.1)

True

In [27]:
np.isscalar([3.2])

False

# 8. Write a numpy program to test element - wise for nan of a given array

In [29]:
import numpy as np
x = np.array([1,0,np.nan,np.inf])
np.isnan(x)

array([False, False,  True, False])

# 9. Write a numpy program to test whether two arrays are element - wise equal with in a tolerance

In [31]:
import numpy as np
np.allclose([1,2],[2,3])


False

In [33]:
np.allclose([1,2],[1,2])

True

# 10. Write a numpy program to create an element - wise comparison (greater, greater equal, less, less equal)

In [35]:
import numpy as np
x = np.array([3,5])
y = np.array([2,3])
np.greater(x,y)

array([ True,  True])

In [37]:
np.greater_equal(x,y)

array([ True,  True])

In [39]:
np.less(x,y)

array([False, False])

In [41]:
np.less_equal(x,y)

array([False, False])

# 11. Write a numpy program to create an element - wise comparison( equal, equal within tolerance) of two given arrays

In [43]:
import numpy as np
x = np.array([72,79,85,90,150,-135,120,-10,60,100])
y = np.array([72,79,85,90,150,-135,120,-10,60,100.00000])
np.equal(x,y)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [46]:
np.allclose(x,y)

True

# 12. Write a numpy program to create an array with the values 1,7,13,105 and determine the size of the memory occupy by the array

In [48]:
import numpy as np
x = np.array([1,7,13,105])
print('the size of the array : ', x.size)

the size of the array :  4


In [50]:
print('memory size of one array element in bytes : ', x.itemsize)

memory size of one array element in bytes :  4


In [52]:
print('memory size of numpy array in bytes : ', x.nbytes)

memory size of numpy array in bytes :  16


# 13. Write a numpy program to create a array of 10 zeros, 10 ones, 10 fives

In [56]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 14. Write a numpy program to create a array of the integers from 30 to 70

In [62]:
import numpy as np
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

# 15. Write a numpy program to create an array of all the even integers from 30 to 70

In [64]:
import numpy as np
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# 16. Write a numpy program to create a 3 * 3 identity matrix

In [66]:
import numpy as np
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 17. Write a numpy program to generate a random number between 0 and 1

In [68]:
np.random.normal(0,1,1)


array([-1.74297814])

# 18. write a numpy program to generate an array of 15 random numbers from standard normal distribution

In [70]:
np.random.normal(0,1,15)

array([-0.55548786,  1.87600007,  0.93445133,  1.05450064,  0.8115531 ,
        0.95547218,  0.66117194,  0.36181327,  0.55245214,  0.15520637,
        0.01995873,  0.10598003,  0.00998179,  0.08632654, -1.06850002])

# 19. Write a numpy program to create a vector with values ranging from 15 to 55 and print all values except the first and the last

In [73]:
import numpy as np
v = np.arange(15,56)
v

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [75]:
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

# 20. Write a numpy program to create a 3 * 4 array using and iterate over it

In [77]:
x = np.arange(10,22).reshape(3,4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [80]:
for i in np.nditer(x):
    print(i)

10
11
12
13
14
15
16
17
18
19
20
21


# 21. Write a numpy program to create a vestor of length 10 with values evenly distributed between 5 and 50

In [82]:
import numpy as np
v = np.linspace(5,50,5)
v

array([ 5.  , 16.25, 27.5 , 38.75, 50.  ])

# 22. Write a numpy program to create a vector with values from 0 to 20 and change the sign of numbers in the range from 9 to 15

In [84]:
import numpy as np
x = np.arange(21)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [86]:
x[(x > 9) & ( x < 15)] * -1

array([-10, -11, -12, -13, -14])

# 23. Write a numpy program to create a vector of length 5 filled with arbitrary integers from 1 to 10

In [89]:
np.random.randint(0,11,5)

array([ 2,  8,  7, 10,  5])

# 24. Write a numpy program to multiply the values of two given vectors

In [91]:
import numpy as np
x = np.random.randint(1,11,5)
y = np.random.randint(1,15,5)
x*y

array([ 42,  32,  88, 104,  48])

# 25. Write a numpy program to create a 3 * 4 matrix filled with values from 10 to 21

In [95]:
import numpy as np
x = np.arange(10,22).reshape(3,4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# 26. Write a numpy program to find the number of rows and columns of a given matrix

In [97]:
import numpy as np
x = np.arange(10,22).reshape(3,4)
x.shape

(3, 4)

# 27. Write a numpy program to create a 3 * 3 identity matrix ie; diagonal elements are 1 and rest are 0

In [99]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 28. Write a numpy program to create a 10 * 10 matrix, in which the elements in the borders will be equal to 1 and inside 0

In [102]:
import numpy as np
x = np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [104]:
x[1:9,1:9] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 29. Write a numpy program to create a 5 * 5 zero matrix in which the elements in the main diagonal equal to 1,2,3,4,5

In [106]:
import numpy as np
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 30. Write a numpy program to create a 4 * 4 matrix in which 0 and 1 are staggered with zeros in the main diagonal

In [109]:
import numpy as np
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [111]:
x[::2,1::2] = 1
x[1::2,::2] = 1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

# 31. Write a numpy program to create a 3 * 3 * 3 array filled with arbitrary values

In [113]:
import numpy as np
np.random.random((3,3,3))

array([[[0.12270886, 0.2531993 , 0.54411856],
        [0.33451434, 0.64925653, 0.86388472],
        [0.74402388, 0.58386368, 0.79214905]],

       [[0.20641326, 0.70297225, 0.96836643],
        [0.38220185, 0.84763311, 0.15325966],
        [0.49675306, 0.06082717, 0.16098504]],

       [[0.36993432, 0.67339973, 0.53495252],
        [0.72618298, 0.68298615, 0.48672522],
        [0.16499207, 0.05353344, 0.04972374]]])

In [115]:
import numpy as np
np.random.randint(10, size = (3,3,3))

array([[[2, 0, 8],
        [6, 8, 9],
        [7, 7, 2]],

       [[6, 0, 3],
        [9, 8, 9],
        [1, 5, 0]],

       [[6, 9, 5],
        [9, 6, 4],
        [4, 4, 9]]])

# 32. Write a numpy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [2]:
import numpy as np
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
np.sum(x)

45

In [4]:
np.sum(x, axis = 1)

array([ 6, 15, 24])

In [6]:
np.sum(x, axis = 0)

array([12, 15, 18])

# 33. Write a numpy program to compute the inner product of two vectors 

In [8]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
np.dot(x,y)

32

# 34. Write a numpy program to add a vector of each row of a given matrix

In [12]:
import numpy as np
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
v = np.array([1,1,0])
result = np.empty_like(m)
result[:4,:4] = m[:4,:4] + v
result

array([[2, 3, 3],
       [5, 6, 6],
       [8, 9, 9]])

# 35. Write a numpy program to save a given array to a binary file

In [16]:
import numpy as np
import os
a = np.arange(20)
np.save('temp_array.npy', a)
print('check if temp_array exist or not')
if os.path.exists('temp_array'):
    x2 = np.load('temp_array.npy')
    np.array_equal(a,x2)

check if temp_array exist or not


# 36. Write a numpy program to save two arrays into a single file in compressed format (.npz format) and load it

In [21]:
import numpy as np
test_array = np.random.rand(3,2)
test_vector = np.random.rand(4)
np.savez_compressed('temp_arra.npz', a = test_array, b = test_vector)
loaded = np.load('temp_arra.npz')
np.array_equal(test_array, loaded['a'])

True

In [23]:
np.array_equal(test_vector, loaded['b'])

True

# 37. Write a numpy program to save a given array to a text file and load it

In [25]:
import numpy as np
x = np.arange(12).reshape(4,3)
np.savetxt('temp.txt', x)
np.loadtxt('temp.txt')


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

# 38. Write a numpy program to convert a given array into bytes and load it as array

In [27]:
import numpy as np
a = np.array([1,2,3,4,5])
a_bytes = a.tobytes()
a2 = np.frombuffer(a_bytes, dtype = a.dtype)
a2

array([1, 2, 3, 4, 5])

In [29]:
np.array_equal(a,a2)

True

# 39. Write a numpy program to convert a given list into an array, then again convert it into a list . Check initial list and final list are equal

In [31]:
import numpy as np
a1 = [1,2,3,4]
x = np.array(a1)
a2 = x.tolist()
np.array_equal(a1,a2)

True

# 40. Write a numpy program to compute the x and y coordinates for points on a sine curve and plot the points using matplotlib

# 41. Write a numpy program to convert numpy dtypes to native python types

In [33]:
import numpy as np
x = np.float32(0)
type(x)

numpy.float32

In [36]:
pyval = x.item()
type(pyval)

float

In [38]:
x = np.array([1,2,3])
type(x)

numpy.ndarray

# 42. Write a numpy program to add elements in a matrix . If an element in the matrix is 0 , we will not add the element below this element

In [43]:
import numpy as np
def sum_matrix_elements(m):
    arra = np.array(m)
    element_sum = 0
    for p in range(len(arra)):
        for q in range(len(arra[p])):
            if arra[p][q] == 0 and p < len(arra) - 1:
                arra[p+1][q] = 0
            element_sum += arra[p][q]
    return element_sum
m = np.array([[1,1,0,2],
             [0,3,0,3],
             [1,0,4,4]])
sum = sum_matrix_elements(m)
sum

14

# 43. Write a numpy program to find the missing data in a given array

In [45]:
import numpy as np
num = np.array([[3,2,np.nan,1],
               [10,12,10,9],
               [5,np.nan,1,np.nan]])
np.isnan(num)

array([[False, False,  True, False],
       [False, False, False, False],
       [False,  True, False,  True]])

# 44. Write a numpy program to check whether two arrays are equal (element wise) or not

In [47]:
import numpy as np
num1 = np.array([0.5,0.2,0.3])
num2 = np.array([0.6,0.5,0.3])
np.equal(num1,num2)

array([False, False,  True])

# 45. Write a numpy program to create one - dimensional array of single, two and three digit numbers

In [50]:
import numpy as np
np.array([1])

array([1])

In [52]:
np.array([12,34])

array([12, 34])

In [54]:
np.array([12,34,56])

array([12, 34, 56])

# 46. Write a numpy program to create a two - dimensional array of specified format

In [56]:
import numpy as np
np.arange(1,151).reshape(15,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

In [58]:
np.arange(1,151).reshape(-1,10)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

In [60]:
np.arange(1,151).reshape(15,-1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

# 47. Write a numpy program to create a one - dimensional array of forty pseudo randomly generated values. Select random numbers from a uniform distribution between 0 and 1

In [62]:
import numpy as np
np.random.seed(10)
np.random.rand(40)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895,
       0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935,
       0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715])

# 48. Write a numpy program to create a two - dimensiona; array with shape(8,5) of random numbers. Select random numbers from a normal distribution (200,7)

In [64]:
import numpy as np
np.random.seed(20)
cbrt = np.cbrt(7)
nd1 = 200
cbrt*np.random.rand(8,5) + nd1

array([[201.12505375, 201.71726458, 201.70543693, 201.56064095,
        200.06865431],
       [201.32328465, 200.72439058, 200.99187576, 201.25861588,
        200.37082213],
       [200.52092254, 201.3746437 , 201.49783202, 201.62661826,
        201.48299013],
       [200.0701363 , 200.22322708, 201.43714828, 200.45760799,
        200.48742637],
       [201.64057862, 201.81686192, 201.07446831, 200.34199483,
        201.47343894],
       [200.94189104, 201.20754367, 201.60590175, 200.88193664,
        200.95252509],
       [201.29966671, 201.24490867, 200.51418679, 200.12878745,
        201.47572146],
       [200.92008955, 200.6297492 , 200.9768212 , 200.50430381,
        200.59398723]])

# 49. Write a numpy program to generate a uniform, non - uniform random sample from a given 1 - D array with and without replacement

In [67]:
import numpy as np
# generate a uniform random sample with replacement
np.random.choice(7,5)


array([6, 4, 3, 3, 0])

In [69]:
# generate a uniform random sample without replacement
np.random.choice(7,5, replace = False)

array([3, 4, 0, 6, 2])

In [71]:
# generate a non - uniform sample with replacement
np.random.choice(7,5, p = [0.1,0.2,0,0.2,0.4,0,0.1])

array([4, 3, 4, 4, 0])

In [74]:
# generate a non - uniform sample without replacement
np.random.choice(7,5, p = [0.1,0.2,0,0.2,0.4,0,0.1], replace = False)

array([6, 4, 3, 1, 0])

# 50. Write a numpy program to create a 4 * 4 array with random values, now create a new array from the said array swapping first and last rows

In [78]:
import numpy as np
nums = np.arange(16).reshape(4,4)
nums

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
nums[[0,-1],:] = nums[[-1,0],:]
nums

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# 51. Write a numpy program to create a new array of given shape(5,6) and type, filled with zeros

In [89]:
import numpy as np
np.zeros(30).reshape(5,6)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 52. Write a numpy program to sort a given array by row and column in ascending order

In [91]:
import numpy as np
array = np.array([[5.54,3.38,7.99],
                 [3.54,4.38,6.99],
                 [1.54,2.29,9.98]])
np.sort(array, axis = 0)

array([[1.54, 2.29, 6.99],
       [3.54, 3.38, 7.99],
       [5.54, 4.38, 9.98]])

In [93]:
np.sort(array, axis = 1)

array([[3.38, 5.54, 7.99],
       [3.54, 4.38, 6.99],
       [1.54, 2.29, 9.98]])

# 53. Write a numpy program to extract all numbers from a given array which are less and greater than a specified number

In [95]:
import numpy as np
array = np.array([[5.54,3.38,7.99],
                 [3.54,4.38,6.99],
                 [1.54,2.29,9.98]])
array[array>5]

array([5.54, 7.99, 6.99, 9.98])

In [98]:
array[array<5]

array([3.38, 3.54, 4.38, 1.54, 2.29])

# 54. Write a numpy program to replace all numbers in a given array which is equal, less and greater to a given number

In [100]:
import numpy as np
array = np.array([[5.54,3.38,7.99],
                 [3.54,4.38,6.99],
                 [1.54,2.29,9.98]])
n = 8.32
r = 18.32
print('replace all elements which are equal to',n,'with',r)
np.where(array == n, r, array)

replace all elements which are equal to 8.32 with 18.32


array([[5.54, 3.38, 7.99],
       [3.54, 4.38, 6.99],
       [1.54, 2.29, 9.98]])

In [102]:
print('replace elements which are less than',n,'with',r)
np.where(array < n, r, array)

replace elements which are less than 8.32 with 18.32


array([[18.32, 18.32, 18.32],
       [18.32, 18.32, 18.32],
       [18.32, 18.32,  9.98]])

In [104]:
print('replace elements which are greater than',n,'with',r)
np.where(array > n, r, array)

replace elements which are greater than 8.32 with 18.32


array([[ 5.54,  3.38,  7.99],
       [ 3.54,  4.38,  6.99],
       [ 1.54,  2.29, 18.32]])

# 55. Write a numpy program to create a array of equal shape and data type of a given array

In [106]:
import numpy as np
array = np.arange(16).reshape(4,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
np.zeros_like(array)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 56. Write a numpy program to create a three - dimensional array with shape (3,5,4) and set to a variable

In [111]:
import numpy as np
np.arange(1,61).reshape(3,5,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]],

       [[41, 42, 43, 44],
        [45, 46, 47, 48],
        [49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60]]])

# 57. Write a numpy program to create a 4 * 4 array, now create a new array from the said array swapping first and last, second and third column

In [113]:
import numpy as np
num = np.random.randint(1,17, size = (4,4))
num

array([[ 2, 15,  9,  2],
       [ 1,  9, 12,  6],
       [ 1, 11,  7,  6],
       [ 5, 12,  3, 10]])

In [115]:
num[:,::-1]

array([[ 2,  9, 15,  2],
       [ 6, 12,  9,  1],
       [ 6,  7, 11,  1],
       [10,  3, 12,  5]])

# 58. Write a numpy program to swap rows and columns of a given array in reverse order

In [118]:
import numpy as np
array = np.arange(16).reshape(4,4)
array[::-1,::-1]
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# 59. Write a numpy program to multiply two given arrays of same size element - by - element

In [ ]:
import numpy as np
num_1 = np.random.randint(1,5, size = (2,3))
num_2 = np.random.randint(1,5, size = (2,3))
np.multiply(num_1)